# Generated by Django 3.2.7 on 2023-08-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(help_text='Enter a unique name for this config.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Only one configuration can be enabled at a time, If this is enabled others will be disabled.')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharges',
            fields=[
                ('wc_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_wait_min', models.IntegerField()),
                ('price_per_min', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_config.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('tmf_id', models.AutoField(primary_key=True, serialize=False)),
                ('after_duration_mins', models.FloatField()),
                ('till_duration_mins', models.FloatField(blank=True, null=True)),
                ('multiplier_factor', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_config.pricingconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('dbp_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('base_distance_km', models.FloatField()),
                ('base_price', models.FloatField()),
                ('additional_distance_price_per_km', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_config.pricingconfiguration')),
            ],
        ),
    ]
